### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit

### ISSUE THREAD

**Issue by ksurendra** [Azure-Samples/storage-blobs-java-v10-quickstart#5] opened 2018-09-17 21:12 UTC
When running the program locally (on my mac), seeing the below error.

```
String accountName = "acsazurestore";
String accountKey = "DefaultEndpointsProtocol=https;AccountName=xx;AccountKey=xxx";
// Create a ServiceURL to call the Blob service. We will also use this to construct the ContainerURL
SharedKeyCredentials creds = new SharedKeyCredentials(accountName, accountKey);
```

`Caused by: java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
	at java.util.Base64$Decoder.decode0(Base64.java:704)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.microsoft.azure.storage.blob.SharedKeyCredentials.<init>(SharedKeyCredentials.java:60)
	at quickstart.Quickstart.main(Quickstart.java:160)
`

I had to comment out the `createTempFile` and `downloadFile` since running locally.

**Comment by darewreck54** [comment] 2018-09-26 19:51
From https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java-v10, it states to use the key and not the connection string for the account key.  

I'm not sure if the document is incorrect or not.  

If I just use the Connection string, I get the same error you have but on windows.  

`java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
    at java.util.Base64$Decoder.decode0 (Base64.java:704)
    at java.util.Base64$Decoder.decode (Base64.java:526)
    at java.util.Base64$Decoder.decode (Base64.java:549)
    at com.microsoft.azure.storage.blob.SharedKeyCredentials.<init> (SharedKeyCredentials.java:60)
    at quickstart.Quickstart.main (Quickstart.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:748)
`

When i use the key, i get the following error: 

```
>> Creating a sample file at: C:\Users\dehang\AppData\Local\Temp\sampleFile638755363879210956.txt
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Service error returned: 400
```

**Comment by darewreck54** [comment] 2018-09-26 20:21
If you step through the code in main, you are required to use the key not the actual connection string.  It will fail to connect on lines:

```
      // Create a ServiceURL to call the Blob service. We will also use this to construct the ContainerURL
            SharedKeyCredentials creds = new SharedKeyCredentials(accountName, accountKey);
            // We are using a default pipeline here, you can learn more about it at https://github.com/Azure/azure-storage-java/wiki/Azure-Storage-Java-V10-Overview
            final ServiceURL serviceURL = new ServiceURL(new URL("http://" + accountName + ".blob.core.windows.net"), StorageURL.createPipeline(creds, new PipelineOptions()));
```

**Comment by dennyac** [comment] 2018-10-02 00:48
@darewreck54 you are correct. We need to use the key and not the actual connection string. 

The storage account you created may have the "Secure transfer required" option as "Enabled". If that is the case, just change the request to https.

That should be fixed in this PR - https://github.com/Azure-Samples/storage-blobs-java-v10-quickstart/pull/6

**Comment by seguler** [comment] 2018-10-19 21:00
Issue fixed. Thanks!

**Closed by seguler** 2018-10-19 21:00 UTC
